import type { Event, Local, Lote, Preview, Saldo } from './types'

export const observed = '2026-10-08T15:00:00Z'
export const local: Local = { id: 'local-1', codigo: 'DEP', nome: 'Depósito', descricao: null, propriedadeId: null, propriedadeNome: null, finalidade: 'Ordinario', ativo: true, revisao: 3, createdAtUtc: observed, updatedAtUtc: observed }
export const destination: Local = { ...local, id: 'local-2', codigo: 'SEG', nome: 'Segregação', finalidade: 'Segregacao', revisao: 4 }
export const item = { id: 'item-1', codigo: 'MIL', nome: 'Milho', descricao: null, categoriaId: null, classe: 'MateriaPrima', unidade: 'kg', podeEntrar: true, podeProduzir: false, usoInterno: true, venda: false, ativo: true, revisao: 7, unidadeFixada: true, createdAtUtc: observed, updatedAtUtc: observed }
export const responsible = { id: 'user-1', nome: 'Marina', ativo: true }
export const lot: Lote = { id: 'lot-1', itemId: item.id, itemCodigo: item.codigo, itemNome: item.nome, itemAtivo: true, codigo: 'MIL-01', codigoExterno: null, origem: 'Recebimento', fonte: 'Documento 01', responsavelId: responsible.id, responsavelNome: responsible.nome, dataOrigem: null, fabricacao: null, coleta: null, validade: null, fonteValidade: null, responsavelValidadeId: null, situacao: 'Liberado', ativo: true, unidade: 'kg', perfilNutricionalId: null, conversaoItemId: null, aplicabilidade: null, revisao: 5, createdAtUtc: observed, updatedAtUtc: observed }
export const stock: Saldo = { loteId: lot.id, localId: local.id, itemId: item.id, itemCodigo: item.codigo, itemNome: item.nome, loteCodigo: lot.codigo, localCodigo: local.codigo, localNome: local.nome, unidade: 'kg', quantidade: '10.000000', quantidadeElegivel: '10.000000', elegivel: true, motivosIndisponibilidade: [], avisos: ['Validade não informada'], revisao: 2, itemRevisao: 7, loteRevisao: 5, localRevisao: 3, observadoEmUtc: observed, sequenciaAte: '9007199254740993' }
export const preview: Preview = { operacao: 'Entrada', loteId: lot.id, unidade: 'kg', quantidade: { declarada: '1', unidadeDeclarada: 'kg', calculada: '1', normalizada: '1', residuo: '0', unidade: 'kg', fator: null, sentido: null, proveniencia: null, exigeAceite: false }, posicoes: [{ loteId: lot.id, localId: local.id, saldoAnterior: '10', saldoPosterior: '11', revisao: 2, revisaoResultante: 3 }], versoesEsperadas: { item: 7, lote: 5, local: 3, posicao: 2, origemLocal: 0, destinoLocal: 0, origemPosicao: 0, destinoPosicao: 0 }, avisos: ['Validade não informada'], observadoEmUtc: observed, sequenciaAte: stock.sequenciaAte }
export const event: Event = { id: 'event-1', sequencia: stock.sequenciaAte, tipo: 'Entrada', autorId: responsible.id, responsavelId: responsible.id, createdAtUtc: observed, dataOperacional: '2026-10-08', dataObservada: '2026-10-08', motivo: 'Conferência', documento: null, eventoReferenciaId: null, algoritmo: 'inventory-f01-v1', snapshotJson: '{"fonte":"Documento 01"}', movimentos: [{ id: 'line-1', ordinal: 1, loteId: lot.id, localId: local.id, itemId: item.id, unidade: 'kg', sentido: 'Entrada', quantidade: '1', quantidadeDeclarada: '1', unidadeDeclarada: 'kg', residuo: '0', saldoAnterior: '10', saldoPosterior: '11', conversaoItemId: null, perfilNutricionalId: null, snapshotJson: '{"itemNome":"Milho"}' }] }
export const page = <T,>(items: T[], current = 1, totalPages = items.length ? 1 : 0) => ({ items, page: current, pageSize: 25, totalItems: items.length, totalPages, observadoEmUtc: observed, sequenciaAte: stock.sequenciaAte })
