export interface InventoryPage<T> { items: T[]; page: number; pageSize: number; totalItems: number; totalPages: number; observadoEmUtc: string; sequenciaAte: string }
export interface Local { id: string; codigo: string; nome: string; descricao: string | null; propriedadeId: string | null; propriedadeNome: string | null; finalidade: 'Ordinario' | 'Segregacao'; ativo: boolean; revisao: number; createdAtUtc: string; updatedAtUtc: string }
export interface Lote { id: string; itemId: string; itemCodigo: string; itemNome: string; itemAtivo: boolean; codigo: string; codigoExterno: string | null; origem: string; fonte: string; responsavelId: string; responsavelNome: string; dataOrigem: string | null; fabricacao: string | null; coleta: string | null; validade: string | null; fonteValidade: string | null; responsavelValidadeId: string | null; situacao: 'Liberado' | 'Bloqueado' | 'Encerrado'; ativo: boolean; unidade: string; perfilNutricionalId: string | null; conversaoItemId: string | null; aplicabilidade: string | null; revisao: number; createdAtUtc: string; updatedAtUtc: string }
export interface Saldo { loteId: string; localId: string; itemId: string; itemCodigo: string; itemNome: string; loteCodigo: string; localCodigo: string; localNome: string; unidade: string; quantidade: string; quantidadeElegivel: string; elegivel: boolean; motivosIndisponibilidade: string[]; avisos: string[]; revisao: number; itemRevisao: number; loteRevisao: number; localRevisao: number; observadoEmUtc: string; sequenciaAte: string }
export interface Responsible { id: string; nome: string; ativo: boolean }
export interface Reconciliation { loteId: string; localId: string; unidade: string; quantidadeLivro: string; quantidadeProjecao: string; diferenca: string }
export interface History { id: string; registroId: string; tipo: string; operacao: string; sequencia: string; autorId: string; createdAtUtc: string; motivo: string; antesJson: string; depoisJson: string }
export interface Movement { id: string; ordinal: number; loteId: string; localId: string; itemId: string; unidade: string; sentido: 'Entrada' | 'Saida'; quantidade: string; quantidadeDeclarada: string; unidadeDeclarada: string; residuo: string; saldoAnterior: string; saldoPosterior: string; conversaoItemId: string | null; perfilNutricionalId: string | null; snapshotJson: string }
export interface Event { id: string; sequencia: string; tipo: string; autorId: string; responsavelId: string; createdAtUtc: string; dataOperacional: string; dataObservada: string | null; motivo: string; documento: string | null; eventoReferenciaId: string | null; algoritmo: string; snapshotJson: string; movimentos: Movement[] }
export interface Versions { item: number; lote: number; local: number; posicao: number; origemLocal: number; destinoLocal: number; origemPosicao: number; destinoPosicao: number }
export interface PhysicalQuantity { declarada: string; unidadeDeclarada: string; calculada: string; normalizada: string; residuo: string; unidade: string; fator: string | null; sentido: string | null; proveniencia: string | null; exigeAceite: boolean }
export interface Preview { operacao: string; loteId: string; unidade: string; quantidade: PhysicalQuantity; posicoes: { loteId: string; localId: string; saldoAnterior: string; saldoPosterior: string; revisao: number; revisaoResultante: number }[]; versoesEsperadas: Versions; avisos: string[]; observadoEmUtc: string; sequenciaAte: string }
export interface QuantizationAcceptance { calculado: string; normalizado: string; residuo: string; motivo: string }
export interface MovementCommand { loteId: string; quantidade: string; unidade: string; responsavelId: string; motivo: string; versoesEsperadas: Versions; localId: string | null; origemLocalId: string | null; destinoLocalId: string | null; conversaoItemId: string | null; quantidadeContada: string | null; aceiteQuantizacao: QuantizationAcceptance | null; dataObservada: string | null; origem: string | null; fonte: string | null; documento: string | null; destino: string | null; evidencia: string | null; eventoReferenciaId: string | null }
export type Operation = 'abertura' | 'entrada' | 'transferencia' | 'saida-manual' | 'consumo-interno' | 'ajuste' | 'segregacao' | 'retorno-segregacao' | 'descarte'
export const operationInfo: Record<Operation, { label: string; endpoint: string; eventType: string; admin: boolean; transfer: boolean }> = {
  abertura: { label: 'Abertura de inventário', endpoint: 'aberturas', eventType: 'Abertura', admin: true, transfer: false },
  entrada: { label: 'Entrada manual', endpoint: 'entradas', eventType: 'Entrada', admin: false, transfer: false },
  transferencia: { label: 'Transferência', endpoint: 'transferencias', eventType: 'Transferencia', admin: false, transfer: true },
  'saida-manual': { label: 'Saída justificada', endpoint: 'saidas-manuais', eventType: 'SaidaManual', admin: false, transfer: false },
  'consumo-interno': { label: 'Consumo interno', endpoint: 'consumos-internos', eventType: 'ConsumoInterno', admin: false, transfer: false },
  ajuste: { label: 'Ajuste de inventário', endpoint: 'ajustes', eventType: 'Ajuste', admin: true, transfer: false },
  segregacao: { label: 'Segregação', endpoint: 'segregacoes', eventType: 'Segregacao', admin: true, transfer: true },
  'retorno-segregacao': { label: 'Retorno da segregação', endpoint: 'retornos-segregacao', eventType: 'RetornoSegregacao', admin: true, transfer: true },
  descarte: { label: 'Descarte', endpoint: 'descartes', eventType: 'Descarte', admin: true, transfer: false },
}
export const operationLabel = (value: string) => Object.entries(operationInfo).find(([slug, info]) => slug === value || info.eventType === value)?.[1].label ?? value
