using GenSW.Application.Animals;
using GenSW.Domain.Animals;
namespace GenSW.Application.Animals.Cruzamentos;
public sealed class CruzamentoService(ICruzamentoRepository repository, TimeProvider timeProvider) : ICruzamentoService
{
 public async Task<CruzamentoResult> CreateAsync(CreateCruzamentoCommand command, CancellationToken ct = default) { ArgumentNullException.ThrowIfNull(command); await ValidateAnimals(command.MachoId, command.FemeaId, ct); var item=Cruzamento.Criar(command.MachoId,command.FemeaId,command.Status,command.DataInicio,command.DataFim,command.Objetivo,command.Observacao,timeProvider.GetUtcNow()); await repository.AddAsync(item,ct); await repository.SaveChangesAsync(ct); return await GetAsync(item.Id,ct); }
 public async Task<CruzamentoResult> GetAsync(Guid id, CancellationToken ct = default) => await repository.GetAsync(id,ct) ?? throw new CruzamentoNotFoundException(id);
 public async Task<PagedCruzamentoResult> ListAsync(CruzamentoListQuery query, CancellationToken ct = default) { if(query.Page<1||query.PageSize is <1 or >100 || (query.Status is not null && !Enum.IsDefined(query.Status.Value))) throw new ArgumentException("List query is invalid."); var page=await repository.ListAsync(query,ct); return new(page.Items,query.Page,query.PageSize,page.TotalItems,(int)Math.Ceiling(page.TotalItems/(double)query.PageSize)); }
 public async Task<CruzamentoResult> UpdateAsync(Guid id, UpdateCruzamentoCommand command, CancellationToken ct = default) { ArgumentNullException.ThrowIfNull(command); var item=await repository.GetForUpdateAsync(id,ct) ?? throw new CruzamentoNotFoundException(id); await ValidateAnimals(command.MachoId,command.FemeaId,ct); item.Atualizar(command.MachoId,command.FemeaId,command.Status,command.DataInicio,command.DataFim,command.Objetivo,command.Observacao,timeProvider.GetUtcNow()); await repository.SaveChangesAsync(ct); return await GetAsync(id,ct); }
 public async Task<CruzamentoResult> SetStatusAsync(Guid id, CruzamentoStatusCommand command, CancellationToken ct = default) { ArgumentNullException.ThrowIfNull(command); var item=await repository.GetForUpdateAsync(id,ct) ?? throw new CruzamentoNotFoundException(id); item.AlterarStatus(command.Status,timeProvider.GetUtcNow()); await repository.SaveChangesAsync(ct); return await GetAsync(id,ct); }
 private async Task ValidateAnimals(Guid machoId,Guid femeaId,CancellationToken ct) { if(machoId==Guid.Empty||femeaId==Guid.Empty) throw new ArgumentException("Male and female are required."); if(machoId==femeaId) throw new CruzamentoConflictException("The same animal cannot be both male and female."); var macho=await repository.GetAnimalAsync(machoId,ct)??throw new AnimalNotFoundException(machoId); var femea=await repository.GetAnimalAsync(femeaId,ct)??throw new AnimalNotFoundException(femeaId); if(macho.Sexo!=SexoAnimal.Macho) throw new CruzamentoConflictException("Male animal sex is incompatible."); if(femea.Sexo!=SexoAnimal.Femea) throw new CruzamentoConflictException("Female animal sex is incompatible."); }
}
