// <auto-generated />
using System;
using GenSW.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GenSW.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GenSWDbContext))]
    [Migration("20261005132012_AddOperationalProperties")]
    partial class AddOperationalProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenSW.Domain.Animals.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int>("Escopo")
                        .HasColumnType("integer");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RacaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VariedadeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInterno")
                        .IsUnique()
                        .HasDatabaseName("UX_Animais_CodigoInterno_CaseInsensitive");

                    b.HasIndex("EspecieId");

                    b.HasIndex("RacaId", "EspecieId");

                    b.HasIndex("VariedadeId", "EspecieId");

                    b.ToTable("Animais", null, t =>
                        {
                            t.HasCheckConstraint("CK_Animais_CodigoInterno_Canonical", "\"CodigoInterno\" <> '' AND \"CodigoInterno\" !~ U&'[\\0009-\\000D\\0085\\00A0\\1680\\2000-\\200A\\2028\\2029\\202F\\205F\\3000]' AND \"CodigoInterno\" !~ '(^ | $|  )'");

                            t.HasCheckConstraint("CK_Animais_Escopo", "\"Escopo\" IN (1, 2)");

                            t.HasCheckConstraint("CK_Animais_Nome_Canonical", "\"Nome\" IS NULL OR (\"Nome\" <> '' AND \"Nome\" !~ U&'[\\0009-\\000D\\0085\\00A0\\1680\\2000-\\200A\\2028\\2029\\202F\\205F\\3000]' AND \"Nome\" !~ '(^ | $|  )')");

                            t.HasCheckConstraint("CK_Animais_Sexo", "\"Sexo\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Animals.CicloReprodutivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CruzamentoId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DataEclosao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicioGestacao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicioIncubacao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataParto")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPostura")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPrevistaParto")
                        .HasColumnType("date");

                    b.Property<int?>("Nascidos")
                        .HasColumnType("integer");

                    b.Property<int?>("NascidosMortos")
                        .HasColumnType("integer");

                    b.Property<int?>("NascidosVivos")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("OvosEclodidos")
                        .HasColumnType("integer");

                    b.Property<int?>("OvosFerteis")
                        .HasColumnType("integer");

                    b.Property<int?>("OvosIncubados")
                        .HasColumnType("integer");

                    b.Property<int?>("OvosInviaveis")
                        .HasColumnType("integer");

                    b.Property<int?>("OvosPostos")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PesoAoNascerGramas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("PesoMedioOvoGramas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Tipo");

                    b.HasIndex("CruzamentoId", "Status");

                    b.ToTable("CiclosReprodutivos", null, t =>
                        {
                            t.HasCheckConstraint("CK_CiclosReprodutivos_Pesos", "(\"PesoMedioOvoGramas\" IS NULL OR \"PesoMedioOvoGramas\" > 0) AND (\"PesoAoNascerGramas\" IS NULL OR \"PesoAoNascerGramas\" > 0)");

                            t.HasCheckConstraint("CK_CiclosReprodutivos_Quantidades", "(\"OvosPostos\" IS NULL OR \"OvosPostos\" >= 0) AND (\"OvosFerteis\" IS NULL OR \"OvosFerteis\" >= 0) AND (\"OvosIncubados\" IS NULL OR \"OvosIncubados\" >= 0) AND (\"OvosEclodidos\" IS NULL OR \"OvosEclodidos\" >= 0) AND (\"OvosInviaveis\" IS NULL OR \"OvosInviaveis\" >= 0) AND (\"Nascidos\" IS NULL OR \"Nascidos\" >= 0) AND (\"NascidosVivos\" IS NULL OR \"NascidosVivos\" >= 0) AND (\"NascidosMortos\" IS NULL OR \"NascidosMortos\" >= 0)");

                            t.HasCheckConstraint("CK_CiclosReprodutivos_Status", "\"Status\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_CiclosReprodutivos_Tipo", "\"Tipo\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Animals.Cruzamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date");

                    b.Property<Guid>("FemeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MachoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FemeaId");

                    b.HasIndex("MachoId");

                    b.HasIndex("Status", "DataInicio");

                    b.ToTable("Cruzamentos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cruzamentos_Animais_Distintos", "\"MachoId\" <> \"FemeaId\"");

                            t.HasCheckConstraint("CK_Cruzamentos_DataFim", "\"DataFim\" IS NULL OR \"DataInicio\" IS NULL OR \"DataFim\" >= \"DataInicio\"");

                            t.HasCheckConstraint("CK_Cruzamentos_Status", "\"Status\" IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Animals.FiliacaoAnimal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataRegistro")
                        .HasColumnType("date");

                    b.Property<Guid>("ProgenitorId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoFiliacao")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProgenitorId");

                    b.HasIndex("AnimalId", "TipoFiliacao")
                        .IsUnique()
                        .HasDatabaseName("UX_FiliacoesAnimal_Animal_Tipo_Ativa")
                        .HasFilter("\"Ativa\" = TRUE");

                    b.HasIndex("ProgenitorId", "AnimalId")
                        .HasDatabaseName("IX_FiliacoesAnimal_DescendentesAtivos")
                        .HasFilter("\"Ativa\"");

                    b.ToTable("FiliacoesAnimal", null, t =>
                        {
                            t.HasCheckConstraint("CK_FiliacoesAnimal_Ativa_DataFim", "(\"Ativa\" AND \"DataFim\" IS NULL) OR (NOT \"Ativa\")");

                            t.HasCheckConstraint("CK_FiliacoesAnimal_Tipo", "\"TipoFiliacao\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Animals.IdentificacaoAnimal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataAplicacao")
                        .HasColumnType("date");

                    b.Property<string>("DescricaoTipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("IdentificacoesAnimal", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentificacoesAnimal_DescricaoTipo_Semantics", "(\"Tipo\" IN (1, 2, 3, 4, 5) AND \"DescricaoTipo\" IS NULL) OR (\"Tipo\" = 6 AND \"DescricaoTipo\" IS NOT NULL AND \"DescricaoTipo\" <> '' AND \"DescricaoTipo\" = btrim(\"DescricaoTipo\"))");

                            t.HasCheckConstraint("CK_IdentificacoesAnimal_Tipo", "\"Tipo\" IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_IdentificacoesAnimal_Valor_Canonical", "\"Valor\" <> '' AND \"Valor\" = btrim(\"Valor\")");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Animals.ImagemAnimal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Altura")
                        .HasColumnType("integer");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArquivoKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataCaptura")
                        .HasColumnType("date");

                    b.Property<int>("Largura")
                        .HasColumnType("integer");

                    b.Property<string>("Legenda")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MiniaturaKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<bool>("Representativa")
                        .HasColumnType("boolean");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .IsUnique()
                        .HasDatabaseName("UX_ImagensAnimal_Representativa")
                        .HasFilter("\"Ativa\" AND \"Representativa\"");

                    b.HasIndex("AnimalId", "Ordem", "CreatedAtUtc", "Id");

                    b.ToTable("ImagensAnimal", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImagensAnimal_Dimensoes", "\"Largura\" BETWEEN 1 AND 2048 AND \"Altura\" BETWEEN 1 AND 2048 AND \"TamanhoBytes\" > 0");

                            t.HasCheckConstraint("CK_ImagensAnimal_Ordem", "\"Ordem\" >= 0");

                            t.HasCheckConstraint("CK_ImagensAnimal_Representativa", "NOT \"Representativa\" OR \"Ativa\"");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Animals.PesagemAnimal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataMedicao")
                        .HasColumnType("date");

                    b.Property<string>("DescricaoMarco")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("IdadeReferenciaDias")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("PesoGramas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TipoMarco")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId", "DataMedicao", "Id");

                    b.ToTable("PesagensAnimal", null, t =>
                        {
                            t.HasCheckConstraint("CK_PesagensAnimal_Idade", "(\"TipoMarco\" = 3 AND \"IdadeReferenciaDias\" IS NOT NULL AND \"IdadeReferenciaDias\" >= 0) OR (\"TipoMarco\" <> 3 AND \"IdadeReferenciaDias\" IS NULL)");

                            t.HasCheckConstraint("CK_PesagensAnimal_Marco", "\"TipoMarco\" BETWEEN 1 AND 6");

                            t.HasCheckConstraint("CK_PesagensAnimal_Outro", "\"TipoMarco\" <> 6 OR (\"DescricaoMarco\" IS NOT NULL AND length(trim(\"DescricaoMarco\")) > 0)");

                            t.HasCheckConstraint("CK_PesagensAnimal_Peso", "\"PesoGramas\" BETWEEN 0.01 AND 99999999.99");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Animals.ProducaoOvo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataPostura")
                        .HasColumnType("date");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("PesoGramas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId", "DataPostura");

                    b.ToTable("ProducoesOvos", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProducoesOvos_PesoGramas", "\"PesoGramas\" > 0");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Animals.Prole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CicloReprodutivoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid?>("LoteOrigemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PesoGramas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeDesdobrada")
                        .HasColumnType("integer");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoRegistro")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Proles_AnimalId")
                        .HasFilter("\"AnimalId\" IS NOT NULL");

                    b.HasIndex("LoteOrigemId");

                    b.HasIndex("CicloReprodutivoId", "LoteOrigemId");

                    b.ToTable("Proles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Proles_Origem", "\"Origem\" IN (1, 2)");

                            t.HasCheckConstraint("CK_Proles_Peso", "\"PesoGramas\" IS NULL OR \"PesoGramas\" > 0");

                            t.HasCheckConstraint("CK_Proles_Quantidade", "\"Quantidade\" > 0 AND (\"TipoRegistro\" <> 1 OR \"Quantidade\" = 1) AND \"QuantidadeDesdobrada\" >= 0 AND \"QuantidadeDesdobrada\" <= \"Quantidade\"");

                            t.HasCheckConstraint("CK_Proles_Sexo", "\"Sexo\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_Proles_TipoRegistro", "\"TipoRegistro\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Animals.RegistroAnimal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("NumeroRegistro")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TipoRegistro")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("RegistrosAnimal", null, t =>
                        {
                            t.HasCheckConstraint("CK_RegistrosAnimal_Ativo_DataFim", "(\"Ativo\" AND \"DataFim\" IS NULL) OR (NOT \"Ativo\" AND \"DataFim\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_RegistrosAnimal_DataFim", "\"DataFim\" IS NULL OR \"DataFim\" >= \"DataInicio\"");

                            t.HasCheckConstraint("CK_RegistrosAnimal_NumeroRegistro_Canonical", "\"NumeroRegistro\" <> '' AND \"NumeroRegistro\" = btrim(\"NumeroRegistro\")");

                            t.HasCheckConstraint("CK_RegistrosAnimal_TipoRegistro", "\"TipoRegistro\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Breeds.Raca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "EspecieId")
                        .HasName("AK_Racas_Id_EspecieId");

                    b.HasIndex("EspecieId");

                    b.ToTable("Racas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Racas_Nome_Canonical", "\"Nome\" <> '' AND \"Nome\" !~ U&'[\\0009-\\000D\\0085\\00A0\\1680\\2000-\\200A\\2028\\2029\\202F\\205F\\3000]' AND \"Nome\" !~ '(^ | $|  )'");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Financial.AuditoriaLancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AntesJson")
                        .HasColumnType("text");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepoisJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoId", "CreatedAtUtc");

                    b.ToTable("AuditoriasLancamento", (string)null);
                });

            modelBuilder.Entity("GenSW.Domain.Financial.CategoriaFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Natureza")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Natureza", "NomeNormalizado")
                        .IsUnique();

                    b.ToTable("CategoriasFinanceiras", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categoria_Natureza", "\"Natureza\" IN (1,2)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("37600000-0000-0000-0000-000000000001"),
                            Ativa = true,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Natureza = 2,
                            Nome = "Insumos",
                            NomeNormalizado = "INSUMOS",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Versao = 1
                        },
                        new
                        {
                            Id = new Guid("37600000-0000-0000-0000-000000000002"),
                            Ativa = true,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Natureza = 2,
                            Nome = "Alimentação",
                            NomeNormalizado = "ALIMENTAÇÃO",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Versao = 1
                        },
                        new
                        {
                            Id = new Guid("37600000-0000-0000-0000-000000000003"),
                            Ativa = true,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Natureza = 2,
                            Nome = "Saúde animal",
                            NomeNormalizado = "SAÚDE ANIMAL",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Versao = 1
                        },
                        new
                        {
                            Id = new Guid("37600000-0000-0000-0000-000000000004"),
                            Ativa = true,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Natureza = 2,
                            Nome = "Serviços",
                            NomeNormalizado = "SERVIÇOS",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Versao = 1
                        },
                        new
                        {
                            Id = new Guid("37600000-0000-0000-0000-000000000005"),
                            Ativa = true,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Natureza = 2,
                            Nome = "Outras despesas",
                            NomeNormalizado = "OUTRAS DESPESAS",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Versao = 1
                        },
                        new
                        {
                            Id = new Guid("37600000-0000-0000-0000-000000000006"),
                            Ativa = true,
                            Codigo = "VENDA_ANIMAIS",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Natureza = 1,
                            Nome = "Venda de animais",
                            NomeNormalizado = "VENDA DE ANIMAIS",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Versao = 1
                        },
                        new
                        {
                            Id = new Guid("37600000-0000-0000-0000-000000000007"),
                            Ativa = true,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Natureza = 1,
                            Nome = "Outras receitas",
                            NomeNormalizado = "OUTRAS RECEITAS",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Versao = 1
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Financial.ConfiguracaoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesCaixa", null, t =>
                        {
                            t.HasCheckConstraint("CK_Caixa_Singleton", "\"Id\" = 1 AND EXTRACT(DAY FROM \"DataInicio\") = 1");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Financial.FechamentoCaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Despesas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("Mes")
                        .HasColumnType("date");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("QuantidadeDespesas")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeReceitas")
                        .HasColumnType("integer");

                    b.Property<decimal>("Receitas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SaldoAbertura")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("SaldoConferido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SaldoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Mes")
                        .IsUnique();

                    b.ToTable("FechamentosCaixa", (string)null);
                });

            modelBuilder.Entity("GenSW.Domain.Financial.IdempotenciaFinanceira", b =>
                {
                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Operacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Chave")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RespostaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AutorId", "Operacao", "Chave");

                    b.ToTable("IdempotenciasFinanceiras", (string)null);
                });

            modelBuilder.Entity("GenSW.Domain.Financial.LancamentoCaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataMovimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LancamentoOriginalId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoAjuste")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("LancamentoOriginalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Caixa_ReversaoOriginal")
                        .HasFilter("\"Origem\" = 2");

                    b.HasIndex("PessoaId");

                    b.HasIndex("DataMovimento", "Id");

                    b.ToTable("LancamentosCaixa", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lancamento_Enums", "\"Tipo\" IN (1,2) AND \"FormaPagamento\" BETWEEN 1 AND 5 AND \"Origem\" BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_Lancamento_Origem", "(\"Origem\" = 1 AND \"LancamentoOriginalId\" IS NULL) OR (\"Origem\" <> 1 AND \"LancamentoOriginalId\" IS NOT NULL AND length(trim(\"MotivoAjuste\")) > 0)");

                            t.HasCheckConstraint("CK_Lancamento_Valor", "\"Valor\" > 0");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Financial.MesCaixa", b =>
                {
                    b.Property<DateOnly>("Mes")
                        .HasColumnType("date");

                    b.Property<bool>("Fechado")
                        .HasColumnType("boolean");

                    b.Property<int>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Mes");

                    b.ToTable("MesesCaixa", (string)null);
                });

            modelBuilder.Entity("GenSW.Domain.People.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Pessoas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pessoas_TipoPessoa", "\"TipoPessoa\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Properties.Propriedade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasIndex("NomeNormalizado")
                        .IsUnique()
                        .HasDatabaseName("UX_Propriedades_Nome_CaseInsensitive");

                    b.HasIndex("Ativo", "Nome", "Id");

                    b.ToTable("Propriedades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Propriedades_Nome_Canonical", "\"Nome\" <> '' AND \"Nome\" !~ U&'[\\0009-\\000D\\0085\\00A0\\1680\\2000-\\200A\\2028\\2029\\202F\\205F\\3000]' AND \"Nome\" !~ '(^ | $|  )'");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Properties.VinculoAnimalPropriedade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .IsUnique()
                        .HasDatabaseName("UX_VinculosAnimalPropriedade_Animal_Atual")
                        .HasFilter("\"DataFim\" IS NULL");

                    b.HasIndex("PropriedadeId", "DataFim");

                    b.HasIndex("AnimalId", "DataInicio", "CreatedAtUtc", "Id");

                    b.ToTable("VinculosAnimalPropriedade", null, t =>
                        {
                            t.HasCheckConstraint("CK_VinculosAnimalPropriedade_Periodo", "\"DataFim\" IS NULL OR \"DataFim\" >= \"DataInicio\"");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Species.Especie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeCientifico")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeComum")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Ovipara")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("PesoPadraoOvoGramas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Especies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Especies_NomeCientifico_Canonical", "\"NomeCientifico\" IS NULL OR (\"NomeCientifico\" <> '' AND \"NomeCientifico\" !~ U&'[\\0009-\\000D\\0085\\00A0\\1680\\2000-\\200A\\2028\\2029\\202F\\205F\\3000]' AND \"NomeCientifico\" !~ '(^ | $|  )')");

                            t.HasCheckConstraint("CK_Especies_NomeComum_Canonical", "\"NomeComum\" <> '' AND \"NomeComum\" !~ U&'[\\0009-\\000D\\0085\\00A0\\1680\\2000-\\200A\\2028\\2029\\202F\\205F\\3000]' AND \"NomeComum\" !~ '(^ | $|  )'");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Varieties.ImagemVariedade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Altura")
                        .HasColumnType("integer");

                    b.Property<string>("ArquivoKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataCaptura")
                        .HasColumnType("date");

                    b.Property<int>("Largura")
                        .HasColumnType("integer");

                    b.Property<string>("Legenda")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MiniaturaKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<bool>("Representativa")
                        .HasColumnType("boolean");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VariedadeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VariedadeId")
                        .IsUnique()
                        .HasDatabaseName("UX_ImagensVariedade_Representativa")
                        .HasFilter("\"Ativa\" AND \"Representativa\"");

                    b.HasIndex("VariedadeId", "Ordem", "CreatedAtUtc", "Id");

                    b.ToTable("ImagensVariedade", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImagensVariedade_Dimensoes", "\"Largura\" BETWEEN 1 AND 2048 AND \"Altura\" BETWEEN 1 AND 2048 AND \"TamanhoBytes\" > 0");

                            t.HasCheckConstraint("CK_ImagensVariedade_Ordem", "\"Ordem\" >= 0");

                            t.HasCheckConstraint("CK_ImagensVariedade_Representativa", "NOT \"Representativa\" OR \"Ativa\"");
                        });
                });

            modelBuilder.Entity("GenSW.Domain.Varieties.Variedade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "EspecieId")
                        .HasName("AK_Variedades_Id_EspecieId");

                    b.HasIndex("EspecieId");

                    b.ToTable("Variedades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Variedades_Nome_Canonical", "\"Nome\" <> '' AND \"Nome\" !~ U&'[\\0009-\\000D\\0085\\00A0\\1680\\2000-\\200A\\2028\\2029\\202F\\205F\\3000]' AND \"Nome\" !~ '(^ | $|  )'");
                        });
                });

            modelBuilder.Entity("GenSW.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GenSW.Infrastructure.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("ReplacedBySessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshSessions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GenSW.Domain.Animals.Animal", b =>
                {
                    b.HasOne("GenSW.Domain.Species.Especie", null)
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenSW.Domain.Breeds.Raca", null)
                        .WithMany()
                        .HasForeignKey("RacaId", "EspecieId")
                        .HasPrincipalKey("Id", "EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Animais_Racas_RacaId_EspecieId");

                    b.HasOne("GenSW.Domain.Varieties.Variedade", null)
                        .WithMany()
                        .HasForeignKey("VariedadeId", "EspecieId")
                        .HasPrincipalKey("Id", "EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Animais_Variedades_VariedadeId_EspecieId");
                });

            modelBuilder.Entity("GenSW.Domain.Animals.CicloReprodutivo", b =>
                {
                    b.HasOne("GenSW.Domain.Animals.Cruzamento", null)
                        .WithMany()
                        .HasForeignKey("CruzamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Animals.Cruzamento", b =>
                {
                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("FemeaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("MachoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Animals.FiliacaoAnimal", b =>
                {
                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("ProgenitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Animals.IdentificacaoAnimal", b =>
                {
                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Animals.ImagemAnimal", b =>
                {
                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Animals.PesagemAnimal", b =>
                {
                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Animals.ProducaoOvo", b =>
                {
                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Animals.Prole", b =>
                {
                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenSW.Domain.Animals.CicloReprodutivo", null)
                        .WithMany()
                        .HasForeignKey("CicloReprodutivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenSW.Domain.Animals.Prole", null)
                        .WithMany()
                        .HasForeignKey("LoteOrigemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GenSW.Domain.Animals.RegistroAnimal", b =>
                {
                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Breeds.Raca", b =>
                {
                    b.HasOne("GenSW.Domain.Species.Especie", null)
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Financial.AuditoriaLancamento", b =>
                {
                    b.HasOne("GenSW.Domain.Financial.LancamentoCaixa", null)
                        .WithMany()
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Financial.FechamentoCaixa", b =>
                {
                    b.HasOne("GenSW.Domain.Financial.MesCaixa", null)
                        .WithMany()
                        .HasForeignKey("Mes")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Financial.LancamentoCaixa", b =>
                {
                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenSW.Domain.Financial.CategoriaFinanceira", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenSW.Domain.Financial.LancamentoCaixa", null)
                        .WithMany()
                        .HasForeignKey("LancamentoOriginalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenSW.Domain.People.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GenSW.Domain.Properties.VinculoAnimalPropriedade", b =>
                {
                    b.HasOne("GenSW.Domain.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenSW.Domain.Properties.Propriedade", null)
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Varieties.ImagemVariedade", b =>
                {
                    b.HasOne("GenSW.Domain.Varieties.Variedade", null)
                        .WithMany()
                        .HasForeignKey("VariedadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Domain.Varieties.Variedade", b =>
                {
                    b.HasOne("GenSW.Domain.Species.Especie", null)
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenSW.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("GenSW.Domain.People.Pessoa", "Pessoa")
                        .WithOne()
                        .HasForeignKey("GenSW.Infrastructure.Identity.ApplicationUser", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("GenSW.Infrastructure.Identity.RefreshSession", b =>
                {
                    b.HasOne("GenSW.Infrastructure.Identity.RefreshSession", "ReplacedBySession")
                        .WithMany()
                        .HasForeignKey("ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenSW.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReplacedBySession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GenSW.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GenSW.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenSW.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GenSW.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
