import { Link } from 'react-router-dom'
import { useEffect, useState, type FormEvent } from 'react'
import { isHttpError } from '../../../../shared/http/httpErrors'
import { createAnimalRegistration, inactivateAnimalRegistration, listAnimalRegistrations } from '../services/registrationsService'
import type { AnimalRegistration, AnimalRegistrationType } from '../types'

const control = 'mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-900'
const button = 'rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60'
function typeLabel(type: AnimalRegistrationType) { return type === 1 ? 'SISBOV' : 'UELN' }

export function AnimalRegistrationsPanel({ animalId, readOnly = false }: { animalId: string; readOnly?: boolean }) {
  const [items, setItems] = useState<AnimalRegistration[] | null>(null); const [error, setError] = useState<string | null>(null)
  const [tipoRegistro, setTipoRegistro] = useState<AnimalRegistrationType>(1); const [numeroRegistro, setNumeroRegistro] = useState(''); const [dataInicio, setDataInicio] = useState(''); const [saving, setSaving] = useState(false)
  const load = () => { setItems(null); setError(null); void listAnimalRegistrations(animalId).then(setItems).catch(() => setError('Não foi possível carregar os registros institucionais.')) }
  useEffect(load, [animalId])
  const create = (event: FormEvent) => { event.preventDefault(); if (readOnly) return; if (!numeroRegistro.trim() || !dataInicio) { setError('Informe número e data de início.'); return }; setSaving(true); setError(null); void createAnimalRegistration(animalId, { tipoRegistro, numeroRegistro: numeroRegistro.trim(), dataInicio }).then(() => { setNumeroRegistro(''); setDataInicio(''); load() }).catch((e: unknown) => setError(isHttpError(e) && e.status === 409 ? 'O registro já existe ou este tipo já está ativo para o animal.' : 'Não foi possível cadastrar o registro.')).finally(() => setSaving(false)) }
  const inactivate = (item: AnimalRegistration) => { if (readOnly) return; const dataFim = new Date().toISOString().slice(0, 10); setSaving(true); setError(null); void inactivateAnimalRegistration(animalId, item.id, dataFim).then(load).catch(() => setError('Não foi possível inativar o registro.')).finally(() => setSaving(false)) }
  return <section aria-labelledby="animal-registrations-heading" className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-slate-900" id="animal-registrations-heading">Registros institucionais</h2><p className="mt-1 text-sm text-slate-600">SISBOV e UELN. A inativação preserva o histórico.</p>{error ? <div><p className="mt-4 text-sm text-red-700" role="alert">{error}</p><button className="mt-2 rounded border px-3 py-2" onClick={load} type="button">Recarregar registros</button></div> : null}{!readOnly && <form className="mt-4 grid gap-3 sm:grid-cols-4" onSubmit={create}><select className={control} onChange={(e) => setTipoRegistro(Number(e.target.value) as AnimalRegistrationType)} value={tipoRegistro}><option value="1">SISBOV</option><option value="2">UELN</option></select><input className={control} onChange={(e) => setNumeroRegistro(e.target.value)} placeholder="Número do registro" value={numeroRegistro} /><input className={control} onChange={(e) => setDataInicio(e.target.value)} type="date" value={dataInicio} /><button className={button} disabled={saving} type="submit">Cadastrar</button></form>}{items === null ? !error && <p className="mt-4" role="status">Carregando registros…</p> : <ul className="mt-5 space-y-2">{items.length === 0 ? <li>Nenhum registro institucional cadastrado.</li> : items.map((item) => <li className="flex flex-wrap items-center justify-between gap-3 rounded border p-3" key={item.id}><span><strong>{typeLabel(item.tipoRegistro)}</strong> — {item.numeroRegistro} <span className="text-slate-600">({item.ativo ? 'Ativo' : `Inativo desde ${item.dataFim}`})</span><span className="block text-sm text-slate-600">Início: {item.dataInicio}</span></span><div className="flex flex-wrap items-center gap-3"><Link className="font-semibold text-emerald-700 underline" to={`/animais/${animalId}/registros/${item.id}`}>Visualizar</Link>{!readOnly && item.ativo ? <button className={button} disabled={saving} onClick={() => inactivate(item)} type="button">Inativar</button> : null}</div></li>)}</ul>}</section>
}
