using GenSW.Application.Animals.Cruzamentos;
using GenSW.Domain.Animals;
namespace GenSW.Application.Animals.CiclosReprodutivos;
public sealed class CicloReprodutivoService(ICicloReprodutivoRepository repository, TimeProvider timeProvider) : ICicloReprodutivoService
{
 public async Task<CicloReprodutivoResult> CreateAsync(Guid cruzamentoId,CicloReprodutivoCommand c,CancellationToken ct=default) { ArgumentNullException.ThrowIfNull(c); if(!await repository.CruzamentoExistsAsync(cruzamentoId,ct)) throw new CruzamentoNotFoundException(cruzamentoId); var x=CicloReprodutivo.Criar(cruzamentoId,c.Tipo,c.Status,c.DataPostura,c.DataInicioIncubacao,c.DataEclosao,c.OvosPostos,c.OvosFerteis,c.OvosIncubados,c.OvosEclodidos,c.OvosInviaveis,c.PesoMedioOvoGramas,c.DataInicioGestacao,c.DataPrevistaParto,c.DataParto,c.Nascidos,c.NascidosVivos,c.NascidosMortos,c.PesoAoNascerGramas,c.Observacao,timeProvider.GetUtcNow()); await repository.AddAsync(x,ct); await repository.SaveChangesAsync(ct); return await GetAsync(x.Id,ct); }
 public async Task<CicloReprodutivoResult> GetAsync(Guid id,CancellationToken ct=default)=>await repository.GetAsync(id,ct)??throw new CicloReprodutivoNotFoundException(id);
 public async Task<PagedCicloReprodutivoResult> ListAsync(CicloReprodutivoListQuery q,CancellationToken ct=default) { if(q.Page<1||q.PageSize is <1 or >100||(q.Tipo is not null&&!Enum.IsDefined(q.Tipo.Value))||(q.Status is not null&&!Enum.IsDefined(q.Status.Value))) throw new ArgumentException("List query is invalid.");var p=await repository.ListAsync(q,ct);return new(p.Items,q.Page,q.PageSize,p.TotalItems,(int)Math.Ceiling(p.TotalItems/(double)q.PageSize)); }
 public async Task<CicloReprodutivoResult> UpdateAsync(Guid id,CicloReprodutivoCommand c,CancellationToken ct=default) { ArgumentNullException.ThrowIfNull(c);var x=await repository.GetForUpdateAsync(id,ct)??throw new CicloReprodutivoNotFoundException(id);x.Atualizar(c.Tipo,c.Status,c.DataPostura,c.DataInicioIncubacao,c.DataEclosao,c.OvosPostos,c.OvosFerteis,c.OvosIncubados,c.OvosEclodidos,c.OvosInviaveis,c.PesoMedioOvoGramas,c.DataInicioGestacao,c.DataPrevistaParto,c.DataParto,c.Nascidos,c.NascidosVivos,c.NascidosMortos,c.PesoAoNascerGramas,c.Observacao,timeProvider.GetUtcNow());await repository.SaveChangesAsync(ct);return await GetAsync(id,ct); }
 public async Task<CicloReprodutivoResult> SetStatusAsync(Guid id,CicloReprodutivoStatusCommand c,CancellationToken ct=default) { ArgumentNullException.ThrowIfNull(c);var x=await repository.GetForUpdateAsync(id,ct)??throw new CicloReprodutivoNotFoundException(id);x.AlterarStatus(c.Status,timeProvider.GetUtcNow());await repository.SaveChangesAsync(ct);return await GetAsync(id,ct); }
}
