import { useEffect, useState, type FormEvent } from 'react'
import { useSearchParams } from 'react-router-dom'
import { isHttpError } from '../../../../shared/http/httpErrors'
import { createFiliation, getPedigree, listFiliations, type Filiation, type FiliationType, type Pedigree } from '../services/filiationsService'
const control='mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-900'; const button='rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60'
const label=(t:FiliationType)=>t===1?'Pai':'Mãe'
function Tree({item}:{item:Pedigree}) { return <li><strong>{item.nome ?? item.codigoInterno}</strong>{item.progenitores.length ? <ul className="ml-5 list-disc">{item.progenitores.map(x=><Tree key={x.animalId} item={x}/>)}</ul>:null}</li> }
export function AnimalFiliationsPanel({animalId}:{animalId:string}) {
 const [params]=useSearchParams();const paiSugerido=params.get('paiSugerido'),maeSugerida=params.get('maeSugerida');const [items,setItems]=useState<Filiation[]|null>(null),[progenitorId,setProgenitorId]=useState(''),[tipo,setTipo]=useState<FiliationType>(1),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false),[pedigree,setPedigree]=useState<Pedigree|null>(null)
 const load=()=>{setItems(null);void listFiliations(animalId).then(setItems).catch(()=>setError('Não foi possível carregar a genealogia.'))};useEffect(load,[animalId])
 const submit=(e:FormEvent)=>{e.preventDefault();if(!progenitorId.trim())return setError('Informe o identificador do progenitor.');setSaving(true);setError(null);void createFiliation(animalId,{progenitorId:progenitorId.trim(),tipoFiliacao:tipo,dataRegistro:null}).then(()=>{setProgenitorId('');load()}).catch(e=>setError(isHttpError(e)&&e.status===409?'A filiação viola uma regra genealógica ou de sexo.':'Não foi possível salvar a filiação.')).finally(()=>setSaving(false))}
 return <section aria-labelledby="animal-filiations-heading" className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold" id="animal-filiations-heading">Genealogia</h2><p className="mt-1 text-sm text-slate-600">A correção preserva o histórico da filiação anterior.</p>{(paiSugerido||maeSugerida)?<div className="mt-3 rounded border border-amber-300 bg-amber-50 p-3 text-sm">Progenitores sugeridos pelo cruzamento: {paiSugerido&&<button type="button" onClick={()=>{setTipo(1);setProgenitorId(paiSugerido)}}>usar Pai sugerido</button>} {maeSugerida&&<button type="button" onClick={()=>{setTipo(2);setProgenitorId(maeSugerida)}}>usar Mãe sugerida</button>}. Confirme cada vínculo em “Definir”; nenhuma filiação é automática.</div>:null}{error?<p className="mt-3 text-red-700" role="alert">{error}</p>:null}<form className="mt-4 grid gap-3 sm:grid-cols-3" onSubmit={submit}><select className={control} value={tipo} onChange={e=>setTipo(Number(e.target.value) as FiliationType)}><option value="1">Pai</option><option value="2">Mãe</option></select><input className={control} placeholder="ID do progenitor" value={progenitorId} onChange={e=>setProgenitorId(e.target.value)}/><button className={button} disabled={saving} type="submit">Definir</button></form>{items===null?<p className="mt-4" role="status">Carregando genealogia…</p>:<ul className="mt-5 space-y-2">{items.length===0?<li>Sem filiações cadastradas.</li>:items.map(x=><li className="rounded border p-3" key={x.id}><strong>{label(x.tipoFiliacao)}</strong> — {x.progenitorId} <span className="text-slate-600">({x.ativa?'Atual':'Histórico'})</span></li>)}</ul>}<button className="mt-4 rounded border px-3 py-2 text-sm" type="button" onClick={()=>void getPedigree(animalId).then(setPedigree).catch(()=>setError('Não foi possível carregar o pedigree.'))}>Visualizar pedigree</button>{pedigree?<ul className="mt-3 list-disc pl-5"><Tree item={pedigree}/></ul>:null}</section>
}
